BEGIN;
CREATE TABLE "genre" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tmdbId" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "UQ_62a0c90aec95f3b2c6d6b7193fc" UNIQUE ("tmdbId"), CONSTRAINT "PK_0285d4f1655d080cfcf7d1ab141" PRIMARY KEY ("id"));
CREATE TABLE "room" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying, "image" character varying, "isPublic" boolean NOT NULL DEFAULT true, "ownerId" integer, CONSTRAINT "UQ_535c742a3606d2e3122f441b26c" UNIQUE ("name"), CONSTRAINT "PK_c6d46db005d623e691b2fbcba23" PRIMARY KEY ("id"));
CREATE TABLE "movie" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "dbId" integer NOT NULL, "title" character varying NOT NULL, "poster_path" character varying, "vote_average" double precision, "overview" character varying, "original_title" character varying, "video" character varying, "release_date" character varying, "imdbRate" double precision, "imdbLink" character varying, "isWatchedTogether" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "addedById" integer, CONSTRAINT "UQ_8ce6944db1273058765a92c64bf" UNIQUE ("dbId"), CONSTRAINT "PK_cb3bb4d61cf764dc035cbedd422" PRIMARY KEY ("id"));
CREATE INDEX "IDX_movie_created_id" ON "movie" ("createdAt", "id") ;
CREATE TABLE "rating" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "rate" integer NOT NULL, "userId" integer, "movieId" uuid, "roomId" integer, CONSTRAINT "UQ_b211c0e1398c965c2a373a81804" UNIQUE ("userId", "movieId", "roomId"), CONSTRAINT "PK_ecda8ad32645327e4765b43649e" PRIMARY KEY ("id"));
CREATE INDEX "IDX_rating_room_movie" ON "rating" ("roomId", "movieId") ;
CREATE TABLE "role" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, CONSTRAINT "UQ_ae4578dcaed5adff96595e61660" UNIQUE ("name"), CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"));
CREATE TABLE "user" ("id" SERIAL NOT NULL, "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "username" character varying(100) NOT NULL, "avatar" character varying(255), "verificationCode" character varying(255), "verificationCodeExpiresAt" TIMESTAMP WITH TIME ZONE, "isEmailVerified" boolean NOT NULL DEFAULT false, "roleId" uuid, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"));
CREATE TYPE "public"."upload_type_enum" AS ENUM('image');
CREATE TABLE "upload" ("id" SERIAL NOT NULL, "name" character varying(1024) NOT NULL, "path" character varying(1024) NOT NULL, "type" "public"."upload_type_enum" NOT NULL DEFAULT 'image', "mime" character varying(128) NOT NULL, "size" character varying(1024) NOT NULL, "createDate" TIMESTAMP NOT NULL DEFAULT now(), "updateDate" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1fe8db121b3de4ddfa677fc51f3" PRIMARY KEY ("id"));
CREATE TYPE "public"."room_invitation_status_enum" AS ENUM('pending', 'accepted', 'declined', 'expired');
CREATE TYPE "public"."room_invitation_userstatus_enum" AS ENUM('member', 'notVerified', 'guest');
CREATE TABLE "room_invitation" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "status" "public"."room_invitation_status_enum" NOT NULL DEFAULT 'pending', "userStatus" "public"."room_invitation_userstatus_enum" NOT NULL DEFAULT 'guest', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "roomId" integer, "invitedById" integer, CONSTRAINT "UQ_31a34814d3264e21e9fdf2a2775" UNIQUE ("email", "roomId"), CONSTRAINT "PK_297d79115071f9e85633ceea6ab" PRIMARY KEY ("id"));
CREATE INDEX "IDX_invitation_room_created" ON "room_invitation" ("roomId", "createdAt", "id") ;
CREATE TABLE "room_invite_link" ("id" SERIAL NOT NULL, "token" character varying NOT NULL, "expiresAt" TIMESTAMP, "maxUsage" integer NOT NULL DEFAULT '0', "uses" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "isActive" boolean NOT NULL DEFAULT true, "roomId" integer, "createdById" integer, CONSTRAINT "UQ_6d91ec91d0c0f73aa190ed92edd" UNIQUE ("token"), CONSTRAINT "PK_d98084bab49668e040b87884996" PRIMARY KEY ("id"));
CREATE INDEX "IDX_invite_link_room_created" ON "room_invite_link" ("roomId", "createdAt", "id") ;
CREATE TABLE "room_users_user" ("roomId" integer NOT NULL, "userId" integer NOT NULL, CONSTRAINT "PK_e811974018202e969e902e794de" PRIMARY KEY ("roomId", "userId"));
CREATE INDEX "IDX_764292bbbb93544a050f844c49" ON "room_users_user" ("roomId") ;
CREATE INDEX "IDX_6c675caa22685ba1e0ebeb0f65" ON "room_users_user" ("userId") ;
CREATE TABLE "room_movies_movie" ("roomId" integer NOT NULL, "movieId" uuid NOT NULL, CONSTRAINT "PK_9d8038f3fc752fd2c9c52fd81b9" PRIMARY KEY ("roomId", "movieId"));
CREATE INDEX "IDX_94139d0944123784a0449f03e1" ON "room_movies_movie" ("roomId") ;
CREATE INDEX "IDX_a8064417b389356ad8a4e95699" ON "room_movies_movie" ("movieId") ;
CREATE TABLE "movie_genres_genre" ("movieId" uuid NOT NULL, "genreId" uuid NOT NULL, CONSTRAINT "PK_aee18568f9fe4ecca74f35891af" PRIMARY KEY ("movieId", "genreId"));
CREATE INDEX "IDX_985216b45541c7e0ec644a8dd4" ON "movie_genres_genre" ("movieId") ;
CREATE INDEX "IDX_1996ce31a9e067304ab168d671" ON "movie_genres_genre" ("genreId") ;
ALTER TABLE "room" ADD CONSTRAINT "FK_65283be59094a73fed31ffeee4e" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "movie" ADD CONSTRAINT "FK_4cca5fe3b242ea618eebf7a4e2b" FOREIGN KEY ("addedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "rating" ADD CONSTRAINT "FK_a6c53dfc89ba3188b389ef29a62" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "rating" ADD CONSTRAINT "FK_1a3badf27affbca3a224f01f7de" FOREIGN KEY ("movieId") REFERENCES "movie"("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "rating" ADD CONSTRAINT "FK_6f0b6108d6f057709003dc86d73" FOREIGN KEY ("roomId") REFERENCES "room"("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "user" ADD CONSTRAINT "FK_c28e52f758e7bbc53828db92194" FOREIGN KEY ("roleId") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "room_invitation" ADD CONSTRAINT "FK_8b3ec61b8a790b70a48b0f95bae" FOREIGN KEY ("roomId") REFERENCES "room"("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "room_invitation" ADD CONSTRAINT "FK_b2ab3a95b8395fc7f8185ed48b3" FOREIGN KEY ("invitedById") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE "room_invite_link" ADD CONSTRAINT "FK_6de330da1a1570f406c8e621037" FOREIGN KEY ("roomId") REFERENCES "room"("id") ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE "room_invite_link" ADD CONSTRAINT "FK_8999a2e03e29f17ab67d92aac0b" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE "room_users_user" ADD CONSTRAINT "FK_764292bbbb93544a050f844c499" FOREIGN KEY ("roomId") REFERENCES "room"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "room_users_user" ADD CONSTRAINT "FK_6c675caa22685ba1e0ebeb0f654" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "room_movies_movie" ADD CONSTRAINT "FK_94139d0944123784a0449f03e17" FOREIGN KEY ("roomId") REFERENCES "room"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "room_movies_movie" ADD CONSTRAINT "FK_a8064417b389356ad8a4e95699e" FOREIGN KEY ("movieId") REFERENCES "movie"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "movie_genres_genre" ADD CONSTRAINT "FK_985216b45541c7e0ec644a8dd4e" FOREIGN KEY ("movieId") REFERENCES "movie"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "movie_genres_genre" ADD CONSTRAINT "FK_1996ce31a9e067304ab168d6715" FOREIGN KEY ("genreId") REFERENCES "genre"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE INDEX IF NOT EXISTS "IDX_user_email_lower" ON "user" (LOWER("email"));
INSERT INTO "role" ("name") VALUES ('user'), ('admin') ON CONFLICT ("name") DO NOTHING;
COMMIT;
